export const iconList = [
    'Accessibility', 'Activity', 'AirVent', 'Airplay',
    'AlarmClockOff', 'AlarmClock', 'Album', 
    'AlignCenterHorizontal', 'AlignCenterVertical', 'AlignCenter', 
    'AlignEndHorizontal', 'AlignEndVertical', 
    'AlignHorizontalDistributeCenter', 'AlignHorizontalDistributeEnd', 
    'AlignHorizontalDistributeStart', 'AlignHorizontalJustifyCenter', 
    'AlignHorizontalJustifyEnd', 'AlignHorizontalJustifyStart', 
    'AlignHorizontalSpaceAround', 'AlignHorizontalSpaceBetween', 
    'AlignJustify', 'AlignLeft', 'AlignRight', 'AlignStartHorizontal', 
    'AlignStartVertical', 'AlignVerticalDistributeCenter', 
    'AlignVerticalDistributeEnd', 'AlignVerticalDistributeStart', 
    'AlignVerticalJustifyCenter', 'AlignVerticalJustifyEnd', 
    'AlignVerticalJustifyStart', 'AlignVerticalSpaceAround', 
    'AlignVerticalSpaceBetween', 'Anchor', 'Angry', 'Annoyed', 'Aperture', 
    'Apple', 'Archive', 'ArrowBigDown', 'ArrowBigLeft', 'ArrowBigRight', 
    'ArrowBigUp', 'ArrowDownCircle', 'ArrowDownLeftCircle', 
    'ArrowDownLeft', 'ArrowDownRightCircle', 'ArrowDownRight', 
    'ArrowDownSquare', 'ArrowDownToLine', 'ArrowDownWideNarrow', 
    'ArrowDownZA', 'ArrowDown', 'ArrowLeftCircle', 'ArrowLeftRight', 
    'ArrowLeftSquare', 'ArrowLeftToLine', 'ArrowLeft', 'ArrowRightCircle', 
    'ArrowRightLeft', 'ArrowRightSquare', 'ArrowRightToLine', 'ArrowRight', 
    'ArrowUpCircle', 'ArrowUpDown', 'ArrowUpLeftCircle', 'ArrowUpLeft', 
    'ArrowUpRightCircle', 'ArrowUpRight', 'ArrowUpSquare', 'ArrowUpToLine', 
    'ArrowUpWideNarrow', 'ArrowUpZA', 'ArrowUp', 'ArrowsUpFromLine', 
    'Asterisk', 'AtSign', 'Atom', 'Award', 'Axe', 'Axis3d', 
];
